#!/usr/bin/env ruby

CONFIG = [
  {
    name: "DuckDuckGo",
    trigger: "dd",
    url: "https://duckduckgo.com/?q=%s"
  },
  {
    name: "GitHub",
    trigger: "gh",
    url: "https://github.com/search?utf8=✓&q=%s"
  },
  {
    name: "Ruby Gems",
    trigger: "ruby",
    url: "https://rubygems.org/search?utf8=%E2%9C%93&query=%s"
  },
  {
    name: "AUR",
    trigger: "aur",
    url: "https://aur.archlinux.org/packages/?O=0&K=%s"
  }
].freeze

def generate_output
  CONFIG.sort_by { |c| c[:trigger] }
        .map { |c| "#{c[:trigger]} #{c[:name]}" }
        .join("\n")
end

if ARGV.length.positive?
  input = ARGV[0]
  mode = config.find { |c| input.start_with? c[:trigger] }
  exit 1 if mode.nil?

  input = input.gsub("#{mode[:trigger]} ", "")
  url = mode[:url].gsub("#{mode[:trigger]} ", "").gsub("%s", input)

  `firefox --new-tab "#{url}"`
else
  puts generate_output
end
